### Importing Data Set

In [5]:
import pandas as pd
import numpy as np

# Creating a manual version of the Uber dataset for practice
data = {
    'START_DATE*': ['1/1/2016 21:11', '1/2/2016 1:25', '1/2/2016 20:25', '1/5/2016 17:31', '1/6/2016 14:42', '10/25/2016 22:15'],
    'END_DATE*': ['1/1/2016 21:17', '1/2/2016 1:37', '1/2/2016 20:38', '1/5/2016 17:45', '1/6/2016 15:49', '10/26/2016 01:10'],
    'CATEGORY*': ['Business', 'Business', 'Business', 'Business', 'Business', 'Personal'],
    'MILES*': [5.1, 5.0, 4.8, 4.7, 63.7, 12.5],
    'PURPOSE*': ['Meal/Entertain', 'Errand/Supplies', 'Meeting', 'Customer Visit', 'Meal/Entertain', 'Medical']
}

df = pd.DataFrame(data)
print("Data Created Locally! No more URL errors.")
df.head()

Data Created Locally! No more URL errors.

      START_DATE*       END_DATE* CATEGORY*  MILES*         PURPOSE*
0  1/1/2016 21:11  1/1/2016 21:17  Business     5.1   Meal/Entertain
1   1/2/2016 1:25   1/2/2016 1:37  Business     5.0  Errand/Supplies
2  1/2/2016 20:25  1/2/2016 20:38  Business     4.8          Meeting
3  1/5/2016 17:31  1/5/2016 17:45  Business     4.7   Customer Visit
4  1/6/2016 14:42  1/6/2016 15:49  Business    63.7   Meal/Entertain

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   START_DATE*  6 non-null      object
 1   END_DATE*    6 non-null      object
 2   CATEGORY*    6 non-null      object
 3   MILES*       6 non-null      float64
 4   PURPOSE*     6 non-null      object
dtypes: float64(1), object(4)
memory usage: 372.0+ bytes

In [7]:
df['START_DATE*']=pd.to_datetime(df['START_DATE*'])
df['END_DATE*']=pd.to_datetime(df['END_DATE*'])

### Extracting Basic Features

In [9]:
df['year']=df['START_DATE*'].dt.year
df['month_name']=df['START_DATE*'].dt.month_name()
df['day_name']=df['START_DATE*'].dt.day_name()
df['hour']=df['START_DATE*'].dt.hour

df['duration']=df['END_DATE*']- df['START_DATE*']

df['is_weekend']=np.where(df['START_DATE*'].dt.dayofweek>4, 1,0)

print("Data types after conversion")
print(df.dtypes)
df.head()

Data types after conversion
START_DATE*     datetime64[ns]
END_DATE*       datetime64[ns]
CATEGORY*               object
MILES*                 float64
PURPOSE*                object
year                     int32
month_name              object
day_name                object
hour                     int32
duration       timedelta64[ns]
is_weekend               int64
dtype: object

,START_DATE*,END_DATE*,CATEGORY*,MILES*,PURPOSE*,year,month_name,day_name,hour,duration,is_weekend
0,2016-01-01 21:11:00,2016-01-01 21:17:00,Business,5.1,Meal/Entertain,2016,January,Friday,21,0 days 00:06:00,0
1,2016-01-02 01:25:00,2016-01-02 01:37:00,Business,5.0,Errand/Supplies,2016,January,Saturday,1,0 days 00:12:00,1
2,2016-01-02 20:25:00,2016-01-02 20:38:00,Business,4.8,Meeting,2016,January,Saturday,20,0 days 00:13:00,1
3,2016-01-05 17:31:00,2016-01-05 17:45:00,Business,4.7,Customer Visit,2016,January,Tuesday,17,0 days 00:14:00,0
4,2016-01-06 14:42:00,2016-01-06 15:49:00,Business,63.7,Meal/Entertain,2016,January,Wednesday,14,0 days 01:07:00,0

In [10]:
df['duration_minutes'] = df['duration'].dt.total_seconds() / 60
df.head()

,START_DATE*,END_DATE*,CATEGORY*,MILES*,PURPOSE*,year,month_name,day_name,hour,duration,is_weekend,duration_minutes
0,2016-01-01 21:11:00,2016-01-01 21:17:00,Business,5.1,Meal/Entertain,2016,January,Friday,21,0 days 00:06:00,0,6.0
1,2016-01-02 01:25:00,2016-01-02 01:37:00,Business,5.0,Errand/Supplies,2016,January,Saturday,1,0 days 00:12:00,1,12.0
2,2016-01-02 20:25:00,2016-01-02 20:38:00,Business,4.8,Meeting,2016,January,Saturday,20,0 days 00:13:00,1,13.0
3,2016-01-05 17:31:00,2016-01-05 17:45:00,Business,4.7,Customer Visit,2016,January,Tuesday,17,0 days 00:14:00,0,14.0
4,2016-01-06 14:42:00,2016-01-06 15:49:00,Business,63.7,Meal/Entertain,2016,January,Wednesday,14,0 days 01:07:00,0,67.0