In [1]:
import pandas as pd

In [5]:
df=pd.read_csv('Student Mental health.csv')

1. How big the data is?

In [9]:
df.shape

(101, 11)

2. How does the data look like?

In [10]:
df.head

<bound method NDFrame.head of                Timestamp Choose your gender   Age What is your course?  \
0         8/7/2020 12:02             Female  18.0          Engineering
1         8/7/2020 12:04               Male  21.0    Islamic education
2         8/7/2020 12:05               Male  19.0                  BIT
3         8/7/2020 12:06             Female  22.0                 Laws
4         8/7/2020 12:13               Male  23.0         Mathemathics
..                   ...                ...   ...                  ...
96   13/07/2020 19:56:49             Female  21.0                  BCS
97   13/07/2020 21:21:42               Male  18.0          Engineering
98   13/07/2020 21:22:56             Female  19.0             Nursing
99   13/07/2020 21:23:57             Female  23.0     Pendidikan Islam
100  18/07/2020 20:16:21               Male  20.0   Biomedical science

    Your current year of Study What is your CGPA? Marital status  \
0                       year 1        3.00 - 3.49             No
1                       year 2        3.00 - 3.49             No
2                       Year 1        3.00 - 3.49             No
3                       year 3        3.00 - 3.49            Yes
4                       year 4        3.00 - 3.49             No
..                         ...                ...            ...
96                      year 1        3.50 - 4.00             No
97                      Year 2        3.00 - 3.49             No
98                      Year 3        3.50 - 4.00            Yes
99                      year 4        3.50 - 4.00             No
100                     Year 2        3.00 - 3.49             No

    Do you have Depression? Do you have Anxiety? Do you have Panic attack?  \
0                       Yes                   No                       Yes
1                        No                  Yes                        No
2                       Yes                  Yes                       Yes
3                       Yes                   No                        No
4                        No                   No                        No
..                      ...                  ...                       ...
96                       No                  Yes                        No
97                      Yes                  Yes                        No
98                      Yes                   No                       Yes
99                       No                   No                        No
100                      No                   No                        No

    Did you seek any specialist for a treatment?
0                                             No
1                                             No
2                                             No
3                                             No
4                                             No
..                                           ...
96                                            No
97                                            No
98                                            No
99                                            No
100                                           No

[101 rows x 11 columns]>

In [11]:
df.sample(5)

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
19,8/7/2020 13:07,Female,18.0,Marine science,year 2,3.50 - 4.00,Yes,Yes,Yes,Yes,No
22,8/7/2020 13:13,Female,24.0,BCS,year 1,3.50 - 4.00,No,No,No,No,No
71,8/7/2020 21:21,Female,18.0,Laws,Year 3,3.50 - 4.00,No,No,No,Yes,No
18,8/7/2020 13:05,Female,20.0,BIT,Year 2,3.50 - 4.00,No,No,Yes,No,No
37,8/7/2020 14:45,Female,19.0,BIT,year 1,2.50 - 2.99,No,Yes,Yes,Yes,No

3. What is the data type of cols?

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 11 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Timestamp                                     101 non-null    object
 1   Choose your gender                            101 non-null    object
 2   Age                                           100 non-null    float64
 3   What is your course?                          101 non-null    object
 4   Your current year of Study                    101 non-null    object
 5   What is your CGPA?                            101 non-null    object
 6   Marital status                                101 non-null    object
 7   Do you have Depression?                       101 non-null    object
 8   Do you have Anxiety?                          101 non-null    object
 9   Do you have Panic attack?                     101 non-null    object
 10  Did you seek any specialist for a treatment?  101 non-null    object
dtypes: float64(1), object(10)
memory usage: 8.8+ KB

4. Are there any missing values?

In [13]:
df.isnull().sum()

Timestamp                                       0
Choose your gender                              0
Age                                             1
What is your course?                            0
Your current year of Study                      0
What is your CGPA?                              0
Marital status                                  0
Do you have Depression?                         0
Do you have Anxiety?                            0
Do you have Panic attack?                       0
Did you seek any specialist for a treatment?    0
dtype: int64

5. How does the data look mathematically?

In [14]:
df.describe()

             Age
count  100.00000
mean    20.53000
std      2.49628
min     18.00000
25%     18.00000
50%     19.00000
75%     23.00000
max     24.00000

In [15]:
df.describe(include='all')

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
count,101,101,100.00000,101,101,101,101,101,101,101,101
unique,92,2,NaN,49,7,6,2,2,2,2,2
top,8/7/2020 12:39,Female,NaN,BCS,year 1,3.50 - 4.00,No,No,No,No,No
freq,3,75,NaN,18,41,47,85,66,67,68,95
mean,NaN,NaN,20.53000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,2.49628,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,18.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,18.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,19.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,23.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,24.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

6. Are there duplicate values?

In [17]:
df.duplicated().sum()

np.int64(0)

7. How is the correlation between cols?

In [19]:
df.corr(numeric_only=True)

     Age
Age  1.0