### Importing data set

In [7]:
import pandas as pd
import numpy as np

data = {
    'Age': [22, 45, 30, 50, 24, 60, 40, 33, 29, 55, 19, 21, 44, 37, 52],
    'Annual_Income': [30000, 100000, 45000, 120000, 35000, 150000, 80000, 60000, 42000, 110000, 25000, 28000, 95000, 72000, 105000],
    'Spending_Score': [15, 80, 35, 90, 20, 95, 50, 45, 30, 85, 10, 12, 75, 55, 88],
    'City': ['New York', 'London', 'London', 'Paris', 'Paris', 'New York', 'London', 'Paris', 'New York', 'London', 'Paris', 'New York', 'London', 'Paris', 'New York'],
    'Membership': ['Normal', 'Premium', 'Normal', 'Premium', 'Normal', 'Premium', 'Normal', 'Normal', 'Normal', 'Premium', 'Normal', 'Normal', 'Premium', 'Normal', 'Premium']
}

df = pd.DataFrame(data)
df.to_csv('practice_data.csv', index=False)
print("Dataset created successfully as 'practice_data.csv'!")

Dataset created successfully as 'practice_data.csv'!

In [9]:
df.head()

   Age  Annual_Income  Spending_Score      City Membership
0   22          30000              15  New York     Normal
1   45         100000              80    London    Premium
2   30          45000              35    London     Normal
3   50         120000              90     Paris    Premium
4   24          35000              20     Paris     Normal

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             15 non-null     int64
 1   Annual_Income   15 non-null     int64
 2   Spending_Score  15 non-null     int64
 3   City            15 non-null     object
 4   Membership      15 non-null     object
dtypes: int64(3), object(2)
memory usage: 732.0+ bytes

In [11]:
df.isnull().sum()

Age               0
Annual_Income     0
Spending_Score    0
City              0
Membership        0
dtype: int64

### Train Test Split

In [12]:
from sklearn.model_selection import train_test_split

X=df.drop('Membership', axis=1)
Y=df['Membership']

X_train, X_test, Y_train, Y_test=train_test_split(X, Y, test_size=0.2, random_state=42)

### Feature Scaling

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import KBinsDiscretizer, Binarizer, OneHotEncoder

trf= ColumnTransformer(transformers=[
    ('income_bining', KBinsDiscretizer(n_bins=3, strategy='quantile', encode='ordinal'), [1]),
    ('spending_binarizer', Binarizer(threshold=50), [2]),
    ('city_encode', OneHotEncoder(drop='first', sparse_output=False), [3])
], remainder='passthrough')

In [21]:
from sklearn.pipeline import Pipeline

pipe=Pipeline([
    ('preprocessing', trf)
])

X_train_transformed=pipe.fit_transform(X_train)
X_test_transformed=pipe.transform(X_test)

final_columns=['Income_Bin', 'High_Spender', 'City_NY', 'City_Paris', 'Age']

X_train_final=pd.DataFrame(X_train_transformed, columns= final_columns)
X_test_final=pd.DataFrame(X_test_transformed, columns= final_columns)

C:\Users\Digital\anaconda3\Lib\site-packages\sklearn\preprocessing\_discretization.py:304: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(

In [25]:
print("Training Data:")
X_train_final

Training Data:

    Income_Bin  High_Spender  City_NY  City_Paris   Age
0          1.0           1.0      0.0         1.0  37.0
1          2.0           1.0      1.0         0.0  60.0
2          0.0           0.0      1.0         0.0  29.0
3          0.0           0.0      0.0         0.0  30.0
4          2.0           1.0      0.0         0.0  45.0
5          2.0           1.0      1.0         0.0  52.0
6          0.0           0.0      0.0         1.0  24.0
7          1.0           0.0      0.0         1.0  33.0
8          0.0           0.0      0.0         1.0  19.0
9          1.0           1.0      0.0         0.0  44.0
10         2.0           1.0      0.0         1.0  50.0
11         1.0           0.0      0.0         0.0  40.0

In [23]:
print("\nTesting Data (First 5 rows):")
display(X_test_final.head())

Testing Data (First 5 rows):

   Income_Bin  High_Spender  City_NY  City_Paris   Age
0         2.0           1.0      0.0         0.0  55.0
1         0.0           0.0      1.0         0.0  21.0
2         0.0           0.0      1.0         0.0  22.0

In [26]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import KBinsDiscretizer, Binarizer, OneHotEncoder
from sklearn.pipeline import Pipeline
import pandas as pd

# 1. Update the Transformer to use 'kmeans'
trf_kmeans = ColumnTransformer([
    ('income_binning', KBinsDiscretizer(n_bins=3, strategy='kmeans', encode='ordinal', random_state=42), [1]),
    ('spending_binarize', Binarizer(threshold=50), [2]),
    ('city_encode', OneHotEncoder(drop='first', sparse_output=False), [3])
], remainder='passthrough')

# 2. Create and Run the Pipeline
pipe_kmeans = Pipeline([
    ('preprocessing', trf_kmeans)
])

X_train_transformed = pipe_kmeans.fit_transform(X_train)

# 3. Convert to DataFrame
final_columns = ['Income_Bin', 'High_Spender', 'City_NY', 'City_Paris', 'Age']
X_train_final_kmeans = pd.DataFrame(X_train_transformed, columns=final_columns)

# 4. Show the result
print("K-Means Binning Results:")
X_train_final_kmeans.head(10)

K-Means Binning Results:

C:\Users\Digital\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1425: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

   Income_Bin  High_Spender  City_NY  City_Paris   Age
0         1.0           1.0      0.0         1.0  37.0
1         2.0           1.0      1.0         0.0  60.0
2         0.0           0.0      1.0         0.0  29.0
3         0.0           0.0      0.0         0.0  30.0
4         1.0           1.0      0.0         0.0  45.0
5         1.0           1.0      1.0         0.0  52.0
6         0.0           0.0      0.0         1.0  24.0
7         0.0           0.0      0.0         1.0  33.0
8         0.0           0.0      0.0         1.0  19.0
9         1.0           1.0      0.0         0.0  44.0

In [27]:
# 1. Reach into the ColumnTransformer to get the binning object
# We use the name we gave it: 'income_binning'
binning_tool = trf_kmeans.named_transformers_['income_binning']

# 2. Print the edges
print("K-Means Salary Ranges:")
print(binning_tool.bin_edges_)

K-Means Salary Ranges:
[array([ 25000.,  65900., 112700., 150000.])]